name:                fp1110924130
version:             0.1.0.0
license:             BSD-3-Clause
author:              "Zerumi"
maintainer:          "367387@edu.itmo.ru"
copyright:           "2024 Zerumi"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitLab at <https://gitlab.se.ifmo.ru/zerumi-functional-programming-2024-labs/fp1_110924_1_30>

dependencies:
- base >= 4.7 && < 5
- validity >= 0.12.0.2
- hspec >= 2.11.9

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  fp1110924130-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp1110924130

tests:
  fp1110924130-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp1110924130
